#!/usr/bin/env python3
"""Generate BRIEF.md from current knowledge base state."""

import sqlite3
import os
import sys
from datetime import datetime, timezone

DB_PATH = os.path.expanduser("~/.claude/knowledge/knowledge.db")
BRIEF_PATH = os.path.expanduser("~/.claude/knowledge/BRIEF.md")


def generate():
    if not os.path.exists(DB_PATH):
        # Empty brief if no DB yet
        with open(BRIEF_PATH, 'w') as f:
            f.write("<!-- Auto-generated by knowledge-base. Do not edit manually. -->\n")
            f.write("# Knowledge Brief\n\nNo facts recorded yet.\n")
        return

    db = sqlite3.connect(DB_PATH)
    db.row_factory = sqlite3.Row

    lines = []
    lines.append("<!-- Auto-generated by knowledge-base. Do not edit manually. -->")
    lines.append(f"<!-- Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} -->")
    lines.append("")
    lines.append("# Knowledge Brief")
    lines.append("")

    # Group entities by type, with their current facts
    entity_types = db.execute(
        "SELECT DISTINCT type FROM entities ORDER BY type"
    ).fetchall()

    entity_count = 0

    for et in entity_types:
        entities = db.execute("""
            SELECT e.* FROM entities e
            WHERE e.type = ?
            AND EXISTS (SELECT 1 FROM facts f WHERE f.entity_id = e.id AND f.valid_to IS NULL)
            ORDER BY e.updated_at DESC
        """, (et['type'],)).fetchall()

        if not entities:
            continue

        # Proper pluralization
        type_plurals = {
            'person': 'People', 'company': 'Companies', 'project': 'Projects',
            'concept': 'Concepts', 'feature': 'Features', 'tool': 'Tools'
        }
        section_title = type_plurals.get(et['type'], f"{et['type'].title()}s")
        lines.append(f"## {section_title}")
        lines.append("")

        for entity in entities:
            entity_count += 1
            facts = db.execute(
                "SELECT attribute, value FROM facts WHERE entity_id = ? AND valid_to IS NULL ORDER BY attribute",
                (entity['id'],)
            ).fetchall()

            # Get current outgoing relations
            rels = db.execute("""
                SELECT r.relation_type, e.name as target FROM relations r
                JOIN entities e ON r.to_entity_id = e.id
                WHERE r.from_entity_id = ? AND r.valid_to IS NULL
            """, (entity['id'],)).fetchall()

            lines.append(f"**{entity['name']}**")
            for f in facts:
                lines.append(f"- {f['attribute']}: {f['value']}")
            for r in rels:
                lines.append(f"- {r['relation_type']}: {r['target']}")
            lines.append("")

    # Active decisions
    decisions = db.execute(
        "SELECT * FROM decisions WHERE status = 'active' ORDER BY decided_at DESC LIMIT 20"
    ).fetchall()

    if decisions:
        lines.append("## Active Decisions")
        lines.append("")
        for d in decisions:
            lines.append(f"**{d['title']}** ({d['decided_at']})")
            if d['rationale']:
                lines.append(f"- {d['rationale']}")
            lines.append("")

    # Stats
    fact_count = db.execute("SELECT COUNT(*) as c FROM facts WHERE valid_to IS NULL").fetchone()['c']
    decision_count = len(decisions)

    lines.append("---")
    lines.append(f"*{entity_count} entities, {fact_count} active facts, {decision_count} active decisions.*")
    lines.append(f"*Deep lookup: `python3 ~/.claude/knowledge/kb.py query \"entity\"`*")

    db.close()

    with open(BRIEF_PATH, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"Generated {BRIEF_PATH} ({len(lines)} lines, {entity_count} entities, {fact_count} facts)")


if __name__ == '__main__':
    generate()
